# Numpy Random Assignment 2018

NumPy is the fundamental package for scientific computing in Python [1]. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.





[1] Numpy https://docs.scipy.org/doc/numpy-1.13.0/user/whatisnumpy.html

##  Generating Random Numbers With NumPy

In [10]:
import numpy as np

In [11]:
#### Generate A Random Number From The Normal Distribution

In [12]:
np.random.normal()

0.9171308882980136

In [13]:
np.random.random_sample()

0.5331690197777363

In [14]:
np.random.random_sample((5,))

array([0.7274234 , 0.0685966 , 0.23292506, 0.57591668, 0.04067824])

In [6]:
####  Generate Four Random Numbers From The Normal Distribution

In [7]:
np.random.normal(size=4)

array([ 0.71550655, -0.15836616,  0.59026006, -1.99539391])

In [8]:
#### Generate Four Random Integers Between 1 and 100

In [9]:
np.random.randint(low=1, high=100, size=4)

array([18, 66, 24, 53])