# Numpy Random Assignment 2018

NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays [1]. Using NumPy, mathematical and logical operations on arrays can be performed. NumPy.Random is a sub-package of the Python NumPy package, and it provides an abundance of useful features for operations on arrays and matrices in Python. It uses a particular algorithm called the Mersenne Twister, to generate pseudorandom numbers [2]. 



------------------------------------------------------




[1] Numpy https://www.tutorialspoint.com/python/python_numpy.htm
[2] Mersenne Twister https://www.oreilly.com/library/view/getting-started-with/9781785285110/ch02s05.html

##  Generating Random Numbers With NumPy

In [10]:
import numpy as np

In [11]:
#### Generate A Random Number From The Normal Distribution

In [12]:
np.random.normal()

0.9171308882980136

In [13]:
np.random.random_sample()

0.5331690197777363

In [14]:
np.random.random_sample((5,))

array([0.7274234 , 0.0685966 , 0.23292506, 0.57591668, 0.04067824])

In [6]:
####  Generate Four Random Numbers From The Normal Distribution

In [7]:
np.random.normal(size=4)

array([ 0.71550655, -0.15836616,  0.59026006, -1.99539391])

In [8]:
#### Generate Four Random Integers Between 1 and 100

In [9]:
np.random.randint(low=1, high=100, size=4)

array([18, 66, 24, 53])